=== yokoyamatoyou/CSVXLM2/data/XSD/ix08_V08.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:mif="urn:hl7-org:v3/mif" xmlns="urn:hl7-org:v3" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:hl7-org:v3" elementFormDefault="qualified">
  <!-- 共通XMLスキーマ読み込み -->
  <xs:include schemaLocation="./coreschemas/datatypes_hcgv08.xsd"/>
  <xs:include schemaLocation="./coreschemas/voc_hcgv08.xsd"/>
  <xs:include schemaLocation="./coreschemas/narrativeBlock_hcgv08.xsd"/>

  <!-- 要素定義 -->
  <xs:element name="index"  type="Index"/>
  <xs:complexType name="Index">
    <xs:all>
      <!-- 1 送付元機関 -->
      <xs:element name="sender"           type="Index.Sender"/>
      <!-- 2 送付先自治体 -->
      <xs:element name="receiver"         type="Index.Receiver"/>
      <!-- 3 作成日 -->
      <xs:element name="creationTime"     type="IVL_TS"/>
      <!-- 4 実施区分 -->
      <xs:element name="serviceEventType">
        <xs:complexType>
          <!-- 4.1 -->
          <xs:attribute name="code"   type="cs" use="required"/>
        </xs:complexType>
      </xs:element>
      <!-- 5 総ファイル数 -->
      <xs:element name="totalRecordCount">
        <xs:complexType>
          <!-- 5.1 -->
          <xs:attribute name="value"  type="Index.TotalRecordCount" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <!-- 送付元機関:定義 -->
  <xs:complexType name="Index.Sender">
    <xs:sequence>
      <!-- 1.1 送付元機関番号 -->
      <xs:element name="id">
        <xs:complexType>
          <!-- 1.1.1 送付元機関番号OID -->
          <xs:attribute name="root"       type="uid"  default="1.2.392.200119.6.102"/>
          <!-- 1.1.2 送付元機関番号 -->
          <xs:attribute name="extension"  type="st"         use="optional"/>
          <!-- 1.1.3 送付元機関番号が登録不要の場合 -->
          <xs:attribute name="nullFlavor" type="NullFlavor" use="optional"/>
        </xs:complexType>
      </xs:element>
      <!-- 1.2 送付元機関名 -->
      <xs:element name="name" type="ON"/>
    </xs:sequence>
  </xs:complexType>
  <!-- 送付先自治体:定義 -->
  <xs:complexType name="Index.Receiver">
    <xs:sequence>
      <!-- 2.1 送付先自治体番号 -->
      <xs:element name="id">
        <xs:complexType>
          <!-- 2.1.1 送付先自治体番号OID -->
          <xs:attribute name="root"       type="uid"  default="1.2.392.200119.6.105"/>
          <!-- 2.1.2 送付先自治体番号 -->
          <xs:attribute name="extension"  type="st"   use="required"/>
        </xs:complexType>
      </xs:element>
      <!-- 2.2 送付先自治体名 -->
      <xs:element name="name" type="ON"/>
    </xs:sequence>
  </xs:complexType>
  <!-- 総ファイル数:定義 -->
  <xs:simpleType name="Index.TotalRecordCount">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="999999"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== yokoyamatoyou/CSVXLM2/data/output_xmls/ix08_output_V08.xml
<?xml version='1.0' encoding='utf-8'?>
<index xmlns="https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000161103.html" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000161103.html ix08_V08.xsd">
  <interactionType code="1"/>
  <creationTime value="20231115"/>
  <sender>
    <id root="1.2.392.200119.6.102" extension="MySenderOrg"/>
  </sender>
  <receiver>
    <id root="1.2.392.200119.6.101" extension="ThePayer"/>
  </receiver>
  <serviceEventType code="1"/>
  <totalRecordCount value="250"/>
</index>

=== yokoyamatoyou/CSVXLM2/XSD/IXtemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--対応仕様書：ix08_doc_v0104-->
<index xmlns="https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000161103.html" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000161103.html ./XSD/ix08_V08.xsd">
	<!-- 種別 -->
	<interactionType code="1"/>
	<!-- 作成年月日 -->
	<creationTime value="99999999"/>
	<!-- 送付元機関） -->
	<sender>
		<id root="1.2.392.200119.6.102" extension="1234567890"/>
	</sender>
	<!-- 送付先機関） -->
	<receiver>
		<id root="1.2.392.200119.6.103" extension="12345678"/>
	</receiver>
	<!-- 実施区分 -->
	<serviceEventType code="1"/>
	<!-- 総ファイル数 -->
	<totalRecordCount value="99"/>
</index>
