=== yokoyamatoyou/CSVXLM2/date/XSD/hc08_V08.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:mif="urn:hl7-org:v3/mif" xmlns="urn:hl7-org:v3" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:hl7-org:v3" elementFormDefault="qualified">
  <!-- 共通XMLスキーマ読み込み -->
  <xs:include schemaLocation="./coreschemas/datatypes_hcgv08.xsd"/>
  <xs:include schemaLocation="./coreschemas/voc_hcgv08.xsd"/>
  <xs:include schemaLocation="./coreschemas/narrativeBlock_hcgv08.xsd"/>
  <!-- 要素定義 -->
  <xs:element name="ClinicalDocument" type="POCD_MT000040.ClinicalDocument"/>
  <xs:complexType name="POCD_MT000040.ClinicalDocument">
    <xs:all>
      <!-- == ヘッダ部 == -->
      <!-- 1 タイプID -->
      <xs:element name="typeId">
        <xs:complexType>
          <xs:complexContent>
            <xs:restriction base="II">
              <xs:attribute name="root"       type="uid"  use="required"  fixed="2.16.840.1.113883.1.3"/>
              <xs:attribute name="extension"  type="st"   use="required"/>
            </xs:restriction>
          </xs:complexContent>
        </xs:complexType>
      </xs:element>
      <!-- 2 生成されたファイルの識別子 -->
      <xs:element name="id"     type="II"/>
      <!-- 3 報告区分コード -->
      <xs:element name="code"   minOccurs="0">
        <xs:complexType>
          <xs:complexContent>
            <xs:restriction base="CD">
              <!-- 3.1 報告区分コードOID -->
              <xs:attribute name="codeSystem" type="uid"  use="optional" fixed="1.2.392.200119.6.1001"/>
              <!-- 3.2 コード -->
              <xs:attribute name="code"       type="cs"   use="required"/>
            </xs:restriction>
          </xs:complexContent>
        </xs:complexType>
      </xs:element>
      <!-- 4 ファイル作成日 -->
      <xs:element name="effectiveTime"        type="TS"/>
      <!-- 5 守秘レベルコード -->
      <xs:element name="confidentialityCode"  type="CE"/>
      <!-- 6 受診者情報 -->
      <xs:element name="recordTarget"         type="POCD_MT000040.RecordTarget"/>
      <!-- 7 ファイル作成機関 -->
      <xs:element name="author"               type="POCD_MT000040.Author"/>
      <!-- 8 ファイル作成管理責任機関 -->
      <xs:element name="custodian"            type="POCD_MT000040.Custodian"/>
      <!-- 9 自治体独自管理番号(住民番号・受診券番号等) -->
      <xs:element name="participant"          type="POCD_MT000040.Participant1" minOccurs="0"/>
      <!-- 10 検診実施情報 -->
      <xs:element name="documentationOf"      type="POCD_MT000040.DocumentationOf"/>
      <!-- 11 ボディ部 -->
      <xs:element name="component"            type="POCD_MT000040.Component2"/>
    </xs:all>
  </xs:complexType>

  <!-- 6 受診者情報 -->
  <xs:complexType name="POCD_MT000040.RecordTarget">
    <xs:sequence>
      <xs:element name="patientRole" type="POCD_MT000040.PatientRole"/>
    </xs:sequence>
  </xs:complexType>
  <!-- 受診者:定義 -->
  <xs:complexType name="POCD_MT000040.PatientRole">
    <xs:sequence>
      <!-- 6.1 保険者番号 ～ 6.4 被保険者証等枝番 -->
      <xs:element name="id"       type="POCD_MT000040.InsuranceId"  minOccurs="0" maxOccurs="unbounded"/>
      <!-- 6.5 受診者住所,連絡先 -->
      <xs:element name="addr"     type="POCD_MT000040.Address"      minOccurs="0"/>
      <!-- 6.7 受診者連絡先 -->
      <xs:element name="telecom"  type="TEL"                        minOccurs="0"/>
      <!-- 6.8 受診者詳細 -->
      <xs:element name="patient"  type="POCD_MT000040.Patient"      minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <!-- 保険資格:定義 -->
  <xs:complexType name="POCD_MT000040.InsuranceId">
    <!-- 6.x.1 OID -->
    <xs:attribute name="root"       type="uid"/>
    <!-- 6.x.2 番号 -->
    <xs:attribute name="extension"  type="st"/>
  </xs:complexType>
  <!-- 受診者詳細:定義 -->
  <xs:complexType name="POCD_MT000040.Patient">
    <xs:sequence>
      <!-- 6.9 氏名 -->
      <xs:element name="name"       type="PN"   minOccurs="0"/>
      <!-- 6.10 男女区分 -->
      <xs:element name="administrativeGenderCode" type="CE"   minOccurs="0"/>
      <!-- 6.11 生年月日 -->
      <xs:element name="birthTime"  type="TS"   minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <!-- 7 ファイル作成機関 -->
  <xs:complexType name="POCD_MT000040.Author">
    <xs:sequence>
      <!-- 7.1 ファイル作成日 -->
      <xs:element name="time"           type="TS"/>
      <!-- 7.2 ファイル作成機関情報 -->
      <xs:element name="assignedAuthor">
        <xs:complexType>
          <xs:sequence>
            <!-- 7.3 ファイル作成機関識別子 -->
            <xs:element name="id"   type="II" maxOccurs="unbounded"/>
            <!-- 7.4 ファイル作成機関 -->
            <xs:element name="representedOrganization" type="POCD_MT000040.Organization" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <!-- 機関:定義 -->
  <xs:complexType name="POCD_MT000040.Organization">
    <xs:sequence>
      <!-- 番号 -->
      <xs:element name="id"       type="II"   minOccurs="0"/>
      <!-- 名称 -->
      <xs:element name="name"     type="ON"/>
      <!-- 連絡先 -->
      <xs:element name="telecom"  type="TEL"  minOccurs="0"/>
      <!-- 所在地/住所 -->
      <xs:element name="addr"     type="POCD_MT000040.Address"  minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <!-- 所在地/住所:定義 -->
  <xs:complexType name="POCD_MT000040.Address" mixed="true">
    <xs:sequence>
      <!-- 郵便番号 -->
      <xs:element name="postalCode" type="POCD_MT000040.PostalCode"/>
    </xs:sequence>
  </xs:complexType>
  <!-- 郵便番号:定義 -->
  <xs:simpleType name="POCD_MT000040.PostalCode">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{3}-[0-9]{4}"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- 8 ファイル作成管理責任機関 ** -->
  <xs:complexType name="POCD_MT000040.Custodian">
    <xs:sequence>
      <xs:element name="assignedCustodian">
        <xs:complexType>
          <xs:sequence>
            <!-- 8.1 ファイル作成管理責任機関 -->
            <xs:element name="representedCustodianOrganization">
              <xs:complexType>
                <xs:sequence>
                  <!-- 8.2 ファイル作成管理責任機関番号 -->
                  <xs:element name="id" type="II" maxOccurs="unbounded"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <!-- 9 自治体独自管理番号(住民番号・受診券番号等) -->
  <xs:complexType name="POCD_MT000040.Participant1">
    <xs:sequence>
      <!-- 9.2 自治体独自管理番号 -->
      <xs:element name="associatedEntity" type="POCD_MT000040.AssociatedEntity"/>
    </xs:sequence>
    <xs:attribute name="typeCode" type="ParticipationType" use="required"/>
  </xs:complexType>

  <!-- 自治体独自管理番号:定義 -->
  <xs:complexType name="POCD_MT000040.AssociatedEntity">
    <xs:sequence>
      <!-- 9.3 自治体独自管理番号 -->
      <xs:element name="id" type="II" minOccurs="0" maxOccurs="unbounded"/>
      <!-- 9.4 管理番号を発行した自治体情報 -->
      <xs:element name="scopingOrganization" type="POCD_MT000040.Organization" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="classCode" type="RoleClassAssociative" use="required"/>
  </xs:complexType>

  <!-- 10 検診実施情報 -->
  <xs:complexType name="POCD_MT000040.DocumentationOf">
    <xs:sequence>
      <xs:element name="serviceEvent" type="POCD_MT000040.ServiceEvent"/>
    </xs:sequence>
  </xs:complexType>
  <!-- 検診実施情報:定義 -->
  <xs:complexType name="POCD_MT000040.ServiceEvent">
    <xs:sequence>
      <!-- 10.1 検診種別 -->
      <xs:element name="code"           type="CD"/>
      <!-- 10.2 検診実施日 -->
      <xs:element name="effectiveTime"  type="IVL_TS"/>
      <!-- 10.3 検診実施機関 -->
      <xs:element name="performer"      type="POCD_MT000040.Performer1"/>
    </xs:sequence>
  </xs:complexType>

  <!-- 検診実施機関:定義 -->
  <xs:complexType name="POCD_MT000040.Performer1">
    <xs:sequence>
      <!-- 10.4 検診実施機関 -->
      <xs:element name="assignedEntity">
        <xs:complexType>
          <xs:sequence>
            <!-- 10.5 検診実施機関識別子 -->
            <xs:element name="id" type="II"/>
            <!-- 10.6 検診実施機関 -->
            <xs:element name="representedOrganization"  type="POCD_MT000040.Organization" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <!-- 10.3.1 -->
    <xs:attribute name="typeCode" type="x_ServiceEventPerformer"  use="required"/>
  </xs:complexType>

  <!-- == ボディ部 == -->
  <xs:complexType name="POCD_MT000040.Component2">
    <xs:sequence>
      <!-- 11 構造化ボディ -->
      <xs:element name="structuredBody">
        <xs:complexType>
          <xs:sequence>
            <!-- 12 セクションへの包含関係 -->
            <xs:element name="component" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>
                  <!-- 13 セクション -->
                  <xs:element name="section"  type="POCD_MT000040.Section"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <!-- セクション:定義 -->
  <xs:complexType name="POCD_MT000040.Section">
    <xs:sequence>
      <!-- 13.1 CDAセクションコード -->
      <xs:element name="code"     type="CE"   minOccurs="0"/>
      <!-- 13.2 CDAセクションタイトル -->
      <xs:element name="title"    type="ST"   minOccurs="0"/>
      <!-- 13.3 CDAセクションの説明ブロック -->
      <xs:element name="text"     type="ST"   minOccurs="0"/>
      <!-- 13.4 CDAセクションの機械可読表現 -->
      <xs:element name="entry"    type="POCD_MT000040.Entry"  minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="POCD_MT000040.Entry">
  <!-- エントリ部:定義 -->
    <xs:sequence>
      <!-- 13.5 検査結果 -->
      <xs:element name="observation"  type="POCD_MT000040.Observation"/>
    </xs:sequence>
  </xs:complexType>
  <!-- 検査結果:定義 -->
  <xs:complexType name="POCD_MT000040.Observation">
    <xs:sequence>
      <xs:element name="id"   type="II" minOccurs="0" maxOccurs="unbounded"/>
      <!-- 13.6 検診項目コード -->
      <xs:element name="code"           minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:complexContent>
            <xs:restriction base="CD">
              <!-- 13.6.1 検診項目コードOID -->
              <xs:attribute name="codeSystem"   type="uid"  use="optional"  default="1.2.392.100495.100.1051"/>
              <!-- 13.6.2 検査項目コード -->
              <xs:attribute name="code"         type="cs"   use="optional"/>
              <!-- 13.6.3 検診項目コード表示名 -->
              <xs:attribute name="displayName"  type="st"   use="optional"/>
            </xs:restriction>
          </xs:complexContent>
        </xs:complexType>
      </xs:element>
      <!-- 13.7 検診結果 -->
      <xs:element name="value"              type="ANY"  minOccurs="0" maxOccurs="unbounded"/>
      <!-- 13.8 一連検査グループ -->
      <xs:element name="entryRelationship"  type="POCD_MT000040.EntryRelationship"  minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <!-- 13.5.1 -->
    <xs:attribute name="classCode"  type="ActClassObservation"          use="required"/>
    <!-- 13.5.2 -->
    <xs:attribute name="moodCode"   type="x_ActMoodDocumentObservation" use="required"/>
  </xs:complexType>
  <!-- 一連検査グループ:定義 -->
  <xs:complexType name="POCD_MT000040.EntryRelationship">
    <xs:sequence>
      <xs:choice>
        <xs:element name="observation" type="POCD_MT000040.Observation"/>
      </xs:choice>
    </xs:sequence>
    <!-- 13.8.1 一連検査グループ 関係性コード -->
    <xs:attribute name="typeCode" type="x_ActRelationshipEntryRelationship" use="required"/>
  </xs:complexType>
</xs:schema>

=== yokoyamatoyou/CSVXLM2/data/output_xmls/cda_headers/hc_header_A0000001.xml
<?xml version='1.0' encoding='utf-8'?>
<ClinicalDocument xmlns="urn:hl7-org:v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dt="https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000161103.html" xsi:schemaLocation="urn:hl7-org:v3 hc08_V08.xsd https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000161103.html coreschemas/datatypes_hcgv08.xsd">
  <typeId root="2.16.840.1.113883.1.3" extension="POCD_HD000040"/>
  <id root="1.2.392.200119.6.1.4" extension="A0000001"/>
  <code code="10" codeSystem="1.2.392.200119.6.1001" displayName="特定健診情報"/>
  <title>特定健診結果報告書</title>
  <effectiveTime value="20231026"/>
  <confidentialityCode code="N" codeSystem="2.16.840.1.113883.5.25"/>
  <languageCode code="ja-JP"/>
  <recordTarget>
    <patientRole>
      <id root="1.2.392.200119.6.201" extension="P12345"/>
      <id root="1.2.392.200119.6.203" extension="INS9876"/>
      <patient>
        <name>
          <dt:family>山田</dt:family>
          <dt:given>太郎</dt:given>
        </name>
        <administrativeGenderCode code="9" codeSystem="1.2.392.200119.6.1104"/>
        <birthTime value="19800515"/>
      </patient>
    </patientRole>
  </recordTarget>
  <author>
    <assignedAuthor>
      <id root="1.2.392.200119.6.102" extension="AUTH_ID_001"/>
    </assignedAuthor>
  </author>
  <custodian>
    <assignedCustodian>
      <representedCustodianOrganization>
        <id root="1.2.392.200119.6.102" extension="CUST_ID_001"/>
      </representedCustodianOrganization>
    </assignedCustodian>
  </custodian>
  <documentationOf>
    <serviceEvent>
      <effectiveTime value="20231001"/>
    </serviceEvent>
  </documentationOf>
</ClinicalDocument>

=== yokoyamatoyou/CSVXLM2/data/output_xmls/cda_checkup_full/hc_cda_CDA_DOC_001.xml
<?xml version='1.0' encoding='utf-8'?>
<ClinicalDocument xmlns="urn:hl7-org:v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dt="https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000161103.html" xsi:schemaLocation="urn:hl7-org:v3 hc08_V08.xsd https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000161103.html coreschemas/datatypes_hcgv08.xsd">
  <typeId root="2.16.840.1.113883.1.3" extension="POCD_HD000040"/>
  <id root="1.2.392.200119.6.1.4" extension="CDA_DOC_001"/>
  <code code="10" codeSystem="1.2.392.200119.6.1001" displayName="特定健診情報"/>
  <title>特定健診結果報告書</title>
  <effectiveTime value="20230510"/>
  <confidentialityCode code="N" codeSystem="2.16.840.1.113883.5.25"/>
  <languageCode code="ja-JP"/>
  <recordTarget>
    <patientRole>
      <id root="1.2.392.200119.6.201" extension="P001"/>
      <id root="1.2.392.200119.6.203" extension="INS001"/>
      <patient>
        <name>
          <dt:family>Tokutei</dt:family>
          <dt:given>Kenzo</dt:given>
        </name>
        <administrativeGenderCode code="Male" codeSystem="1.2.392.200119.6.1104"/>
        <birthTime value="19700101"/>
      </patient>
    </patientRole>
  </recordTarget>
  <author>
    <assignedAuthor>
      <id root="1.2.392.200119.6.102" extension="AUTH_HOSP"/>
    </assignedAuthor>
  </author>
  <custodian>
    <assignedCustodian>
      <representedCustodianOrganization>
        <id root="1.2.392.200119.6.102" extension="CUST_HOSP"/>
      </representedCustodianOrganization>
    </assignedCustodian>
  </custodian>
  <component typeCode="COMP">
    <structuredBody>
      <component>
        <section>
          <code/>
          <title>検査結果</title>
          <text>特定健診の検査結果を以下に示す。</text>
          <entry typeCode="DRIV">
            <observation classCode="OBS" moodCode="EVN">
              <code/>
              <value xsi:type="dt:PQ" value="170" unit="cm"/>
            </observation>
          </entry>
          <entry typeCode="DRIV">
            <observation classCode="OBS" moodCode="EVN">
              <code/>
              <value xsi:type="dt:PQ" value="65" unit="kg"/>
            </observation>
          </entry>
        </section>
      </component>
    </structuredBody>
  </component>
</ClinicalDocument>

=== yokoyamatoyou/CSVXLM2/data/output_xmls/cda_full/hc_cda_CDA_DOC_002.xml
<?xml version='1.0' encoding='utf-8'?>
<ClinicalDocument xmlns="urn:hl7-org:v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dt="https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000161103.html" xsi:schemaLocation="urn:hl7-org:v3 hc08_V08.xsd https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000161103.html coreschemas/datatypes_hcgv08.xsd">
  <typeId root="2.16.840.1.113883.1.3" extension="POCD_HD000040"/>
  <id root="" extension="CDA_DOC_002"/>
  <code code="" codeSystem="" displayName="特定健診情報"/>
  <title>特定健診結果報告書</title>
  <effectiveTime value="20230615"/>
  <confidentialityCode code="N" codeSystem="2.16.840.1.113883.5.25"/>
  <languageCode code="ja-JP"/>
  <recordTarget>
    <patientRole>
      <id root="" extension="P002"/>
      <id root="" extension="INS002"/>
      <patient>
        <name>
          <dt:family>Shido</dt:family>
          <dt:given>Hanako</dt:given>
        </name>
        <administrativeGenderCode code="Female" codeSystem=""/>
        <birthTime value="19850312"/>
      </patient>
    </patientRole>
  </recordTarget>
  <author>
    <assignedAuthor>
      <id root="" extension="AUTH_CLINIC"/>
    </assignedAuthor>
  </author>
  <custodian>
    <assignedCustodian>
      <representedCustodianOrganization>
        <id root="" extension="CUST_CLINIC"/>
      </representedCustodianOrganization>
    </assignedCustodian>
  </custodian>
  <documentationOf>
    <serviceEvent>
      <effectiveTime value="20230601"/>
    </serviceEvent>
  </documentationOf>
  <component typeCode="COMP">
    <structuredBody>
      <component>
        <section>
          <code code="01010" codeSystem="1.2.392.200119.6.1010" displayName="特定健診検査結果"/>
          <title>特定健診検査結果</title>
          <text>特定健診の検査結果を以下に示す。</text>
          <entry typeCode="DRIV">
            <observation classCode="OBS" moodCode="EVN">
              <code code="" codeSystem="" displayName="身長"/>
              <value xsi:type="dt:PQ" value="160" unit="cm"/>
            </observation>
          </entry>
          <entry typeCode="DRIV">
            <observation classCode="OBS" moodCode="EVN">
              <code code="" codeSystem="" displayName="体重"/>
              <value xsi:type="dt:PQ" value="55" unit="kg"/>
            </observation>
          </entry>
          <entry typeCode="DRIV">
            <observation classCode="OBS" moodCode="EVN">
              <code code="3" codeSystem="" displayName=""/>
              <value xsi:type="dt:CD" code="3" codeSystem="" displayName="不明"/>
            </observation>
          </entry>
        </section>
      </component>
    </structuredBody>
  </component>
</ClinicalDocument>

=== yokoyamatoyou/CSVXLM2/XSD/CDAtemplate-hc18.xml
<?xml version="1.0" encoding="UTF-8"?><ClinicalDocument xmlns="urn:hl7-org:v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:hl7-org:v3 ../XSD/hc08_V08.xsd">  <!--   2021年度改訂対応ファイル produced by CC2CX2021  -->  <!--   ヘッダ情報記述部　-->  <!--CDAのデフォルト-->  <typeId root="2.16.840.1.113883.1.3" extension="POCD_HD000040"/>  <id nullFlavor="NI"/>  <!--報告区分コード -->  <code code="99999999" codeSystem="1.2.392.200119.6.1001"/>  <!--文書発行日（西暦）-->  <effectiveTime value="99999999"/>  <confidentialityCode code="N"/>  <!--受診者情報-->  <recordTarget>    <patientRole>      <!-- 保険者番号 -->      <id extension="99999999" root="1.2.392.200119.6.101"/>      <!-- 被保険者証等記号 -->      <id extension="99999999" root="1.2.392.200119.6.204"/>      <!-- 被保険者証等番号 -->      <id extension="99999999" root="1.2.392.200119.6.205"/>      <!-- 被保険者証等番号枝番 2021.02 -->      <id extension="99999999" root="1.2.392.200119.6.211"/>      <!--受診者 -->      <addr>        <postalCode>99999999</postalCode>				99999999			</addr>      <patient>        <name>99999999</name>        <!-- 性別 -->        <administrativeGenderCode code="99999999" codeSystem="1.2.392.200119.6.1104"/>        <!-- 生年月日 -->        <birthTime value="99999999"/>      </patient>    </patientRole>  </recordTarget>  <!--Author -->  <author>    <!-- 作成日 -->    <time value="99999999"/>    <assignedAuthor>      <id nullFlavor="NI"/>      <representedOrganization>        <!--作成機関のID番号 -->        <id extension="99999999" root="1.2.392.200119.6.102"/>        <!-- 作成機関名  -->        <name>99999999</name>        <telecom value="99999999"/>        <addr>          <postalCode>99999999</postalCode>					99999999					</addr>      </representedOrganization>    </assignedAuthor>  </author>  <custodian>    <assignedCustodian>      <representedCustodianOrganization>        <id nullFlavor="NI"/>      </representedCustodianOrganization>    </assignedCustodian>  </custodian>  <participant typeCode="HLD">    <!-- 受診券  -->    <functionCode code="1" codeSystem="1.2.392.200119.6.208"/>    <time>      <!--有効期限 -->      <high value="99999999"/>    </time>    <associatedEntity classCode="IDENT">      <!-- 番号 -->      <id extension="99999999" root="1.2.392.200119.6.209.99999999"/>      <!-- 保険者情報 -->      <scopingOrganization>        <!--保険者番号 -->        <id extension="99999999" root="1.2.392.200119.6.101"/>      </scopingOrganization>    </associatedEntity>  </participant>  <!--健診実施情報-->  <documentationOf>    <serviceEvent>      <!-- プログラム種別コード -->      <code code="99999999" codeSystem="1.2.392.200119.6.1002"/>      <!--実施日-->      <effectiveTime value="99999999"/>      <performer typeCode="PRF">        <assignedEntity>          <id nullFlavor="NI"/>          <representedOrganization>            <!--実施機関番号 -->            <id extension="99999999" root="1.2.392.200119.6.102"/>            <!-- 実施組織名 -->            <name>99999999</name>            <telecom value="99999999"/>            <addr>              <postalCode>99999999</postalCode>							99999999							</addr>          </representedOrganization>        </assignedEntity>      </performer>    </serviceEvent>  </documentationOf>  <!--   結果記述部 -->  <component>    <structuredBody>      <component>        <section>          <code code="99999999" codeSystem="1.2.392.200119.6.1010" displayName="99999999"/>          <title>99999999</title>          <text>            <list>              <item>99999999</item>            </list>          </text>          <!--[OBS]-->          <entry>            <observation classCode="OBS" moodCode="EVN">              <code code="99999999"/>            </observation>          </entry>        </section>      </component>    </structuredBody>  </component></ClinicalDocument>
