=== yokoyamatoyou/CSVXLM2/data/xsd_schemas/hg08_V08.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="urn:hl7-org:v3"
           xmlns:dt="https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000161103.html"
           targetNamespace="urn:hl7-org:v3" elementFormDefault="qualified">

  <xs:import namespace="https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000161103.html" schemaLocation="coreschemas/datatypes_hcgv08.xsd"/>

  <xs:element name="ClinicalDocument">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="typeId" type="dt:II"/>
        <xs:element name="id" type="dt:II"/>
        <xs:element name="code" type="dt:CD"/>
        <xs:element name="title" type="dt:textType" minOccurs="0"/>
        <xs:element name="effectiveTime" type="dt:TS"/>
        <xs:element name="confidentialityCode" type="dt:CD"/>
        <xs:element name="languageCode" type="dt:CD" minOccurs="0"/>
        <xs:element name="recordTarget"><xs:complexType><xs:sequence><xs:element name="patientRole"><xs:complexType><xs:sequence>
          <xs:element name="id" type="dt:II" maxOccurs="unbounded"/>
          <xs:element name="patient"><xs:complexType><xs:sequence>
            <xs:element name="name" type="dt:PN"/><xs:element name="administrativeGenderCode" type="dt:CD"/><xs:element name="birthTime" type="dt:TS"/>
          </xs:sequence></xs:complexType></xs:element></xs:sequence></xs:complexType></xs:element></xs:sequence></xs:complexType></xs:element>
        <xs:element name="author"><xs:complexType><xs:sequence><xs:element name="assignedAuthor"><xs:complexType><xs:sequence><xs:element name="id" type="dt:II"/></xs:sequence></xs:complexType></xs:element></xs:sequence></xs:complexType></xs:element>
        <xs:element name="custodian"><xs:complexType><xs:sequence><xs:element name="assignedCustodian"><xs:complexType><xs:sequence><xs:element name="representedCustodianOrganization"><xs:complexType><xs:sequence><xs:element name="id" type="dt:II"/></xs:sequence></xs:complexType></xs:element></xs:sequence></xs:complexType></xs:element></xs:sequence></xs:complexType></xs:element>
        <xs:element name="documentationOf" minOccurs="0"><xs:complexType><xs:sequence><xs:element name="serviceEvent"><xs:complexType><xs:sequence><xs:element name="effectiveTime" type="dt:IVL_TS"/></xs:sequence></xs:complexType></xs:element></xs:sequence></xs:complexType></xs:element>
        <xs:element name="component" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="structuredBody">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="component" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="section">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="code" type="dt:CD"/>
                                <xs:element name="title" type="dt:textType" minOccurs="0"/>
                                <xs:element name="text" type="dt:textType" minOccurs="0"/>
                                <xs:element name="entry" minOccurs="0" maxOccurs="unbounded">
                                  <xs:complexType><xs:sequence><xs:element name="observation"><xs:complexType><xs:sequence>
                                    <xs:element name="code" type="dt:CD"/>
                                    <xs:element name="value" type="xs:anyType"/>
                                  </xs:sequence><xs:attribute name="classCode" type="xs:string" fixed="OBS"/><xs:attribute name="moodCode" type="xs:string" fixed="EVN"/></xs:complexType></xs:element></xs:sequence><xs:attribute name="typeCode" type="xs:string" fixed="DRIV"/></xs:complexType></xs:element>
                              </xs:sequence></xs:complexType></xs:element>
                        </xs:sequence></xs:complexType></xs:element>
                  </xs:sequence></xs:complexType></xs:element>
            </xs:sequence><xs:attribute name="typeCode" type="xs:string" fixed="COMP"/></xs:complexType></xs:element>
      </xs:sequence></xs:complexType></xs:element>
</xs:schema>

=== yokoyamatoyou/CSVXLM2/data/output_xmls/cda_guidance_full/hg_cda_HG_DOC_001.xml
<?xml version='1.0' encoding='utf-8'?>
<ClinicalDocument xmlns="urn:hl7-org:v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dt="https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000161103.html" xsi:schemaLocation="urn:hl7-org:v3 hg08_V08.xsd https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000161103.html coreschemas/datatypes_hcgv08.xsd">
  <typeId root="2.16.840.1.113883.1.3" extension="POCD_HD000040"/>
  <id root="1.2.392.200119.6.1.5" extension="HG_DOC_001"/>
  <code code="20" codeSystem="1.2.392.200119.6.1001" displayName="特定保健指導情報"/>
  <title>積極支援プログラム</title>
  <effectiveTime value="20231201"/>
  <confidentialityCode code="N" codeSystem="2.16.840.1.113883.5.25"/>
  <languageCode code="ja-JP"/>
  <recordTarget>
    <patientRole>
      <id root="1.2.392.200119.6.201" extension="P003"/>
      <id root="1.2.392.200119.6.203" extension="INS003"/>
      <patient>
        <name>
          <dt:family>指導</dt:family>
          <dt:given>良子</dt:given>
        </name>
        <administrativeGenderCode code="Female" codeSystem="1.2.392.200119.6.1104"/>
        <birthTime value="19780720"/>
      </patient>
    </patientRole>
  </recordTarget>
  <author>
    <assignedAuthor>
      <id root="1.2.392.200119.6.102.1" extension="AUTH_GUIDE_CTR"/>
    </assignedAuthor>
  </author>
  <custodian>
    <assignedCustodian>
      <representedCustodianOrganization>
        <id root="1.2.392.200119.6.102.1" extension="CUST_GUIDE_CTR"/>
      </representedCustodianOrganization>
    </assignedCustodian>
  </custodian>
  <documentationOf>
    <serviceEvent>
      <effectiveTime>
        <dt:low value="20231101"/>
        <dt:high value="20231130"/>
      </effectiveTime>
    </serviceEvent>
  </documentationOf>
  <component typeCode="COMP">
    <structuredBody>
      <component>
        <section>
          <code/>
        </section>
      </component>
    </structuredBody>
  </component>
</ClinicalDocument>

=== yokoyamatoyou/CSVXLM2/data/output_xmls/cda_guidance_headers/hg_header_HG_DOC_001.xml
<?xml version='1.0' encoding='utf-8'?>
<ClinicalDocument xmlns="urn:hl7-org:v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dt="https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000161103.html" xsi:schemaLocation="urn:hl7-org:v3 hg08_V08.xsd https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000161103.html coreschemas/datatypes_hcgv08.xsd">
  <typeId root="2.16.840.1.113883.1.3" extension="POCD_HD000040"/>
  <id root="" extension="HG_DOC_001"/>
  <code code="" codeSystem="" displayName="特定保健指導情報"/>
  <title>積極支援プログラム</title>
  <effectiveTime value="20231201"/>
  <confidentialityCode code="N" codeSystem="2.16.840.1.113883.5.25"/>
  <languageCode code="ja-JP"/>
  <recordTarget>
    <patientRole>
      <id root="" extension="P003"/>
      <id root="" extension="INS003"/>
      <patient>
        <name>
          <dt:family>指導</dt:family>
          <dt:given>良子</dt:given>
        </name>
        <administrativeGenderCode code="Female" codeSystem=""/>
        <birthTime value="19780720"/>
      </patient>
    </patientRole>
  </recordTarget>
  <author>
    <assignedAuthor>
      <id root="" extension="AUTH_GUIDE_CTR"/>
    </assignedAuthor>
  </author>
  <custodian>
    <assignedCustodian>
      <representedCustodianOrganization>
        <id root="" extension="CUST_GUIDE_CTR"/>
      </representedCustodianOrganization>
    </assignedCustodian>
  </custodian>
  <documentationOf>
    <serviceEvent>
      <effectiveTime>
        <dt:low value="20231101"/>
        <dt:high value="20231130"/>
      </effectiveTime>
    </serviceEvent>
  </documentationOf>
</ClinicalDocument>

=== yokoyamatoyou/CSVXLM2/data/output_xmls/cda_guidance_full/hg_cda_HG_DOC_002.xml
<?xml version='1.0' encoding='utf-8'?>
<ClinicalDocument xmlns="urn:hl7-org:v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dt="https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000161103.html" xsi:schemaLocation="urn:hl7-org:v3 hg08_V08.xsd https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000161103.html coreschemas/datatypes_hcgv08.xsd">
  <typeId root="2.16.840.1.113883.1.3" extension="POCD_HD000040"/>
  <id root="1.2.392.200119.6.1.5" extension="HG_DOC_002"/>
  <code code="20" codeSystem="1.2.392.200119.6.1001" displayName="特定保健指導情報"/>
  <title>動機づけ支援ライト</title>
  <effectiveTime value="20231205"/>
  <confidentialityCode code="N" codeSystem="2.16.840.1.113883.5.25"/>
  <languageCode code="ja-JP"/>
  <recordTarget>
    <patientRole>
      <id root="1.2.392.200119.6.201" extension="P004"/>
      <id root="1.2.392.200119.6.203" extension="INS004"/>
      <patient>
        <name>
          <dt:family>保健</dt:family>
          <dt:given>太郎</dt:given>
        </name>
        <administrativeGenderCode code="Male" codeSystem="1.2.392.200119.6.1104"/>
        <birthTime value="19650210"/>
      </patient>
    </patientRole>
  </recordTarget>
  <author>
    <assignedAuthor>
      <id root="1.2.392.200119.6.102.1" extension="AUTH_GUIDE_CTR"/>
    </assignedAuthor>
  </author>
  <custodian>
    <assignedCustodian>
      <representedCustodianOrganization>
        <id root="1.2.392.200119.6.102.1" extension="CUST_GUIDE_CTR"/>
      </representedCustodianOrganization>
    </assignedCustodian>
  </custodian>
  <documentationOf>
    <serviceEvent>
      <effectiveTime>
        <dt:low value="20231105"/>
        <dt:high value="20231204"/>
      </effectiveTime>
    </serviceEvent>
  </documentationOf>
  <component typeCode="COMP">
    <structuredBody>
      <component>
        <section>
          <code code=""/>
          <title>特定保健指導共通情報</title>
          <text>特定保健指導の共通情報を以下に示す。</text>
        </section>
      </component>
      <component>
        <section>
          <code code=""/>
          <title>初回面接情報</title>
          <entry typeCode="DRIV">
            <observation classCode="OBS" moodCode="EVN">
              <code code=""/>
              <value xsi:type="dt:INT" value="80"/>
            </observation>
          </entry>
        </section>
      </component>
    </structuredBody>
  </component>
</ClinicalDocument>
